### PR TITLE
switched to https-only

### PR DESCRIPTION
**Pull request by lucendio**

### CODE REVIEW

**Comment by reywood** [comment]
What's the purpose of this? Simply loading the analytics script over https does not cause your analytics to be sent over SSL.

**Comment by lucendio** [comment]
that I am aware of, but thanks for pointing me to this information.
My intention is to minimize the chance of man-in-the-middle attacks.

**Comment by reywood** [comment]
Can't find anything that points to a concern in that regard. Do you have any references? I ask because that would mean someone has hijacked the user's DNS or a key router between them and Google. In that case, I think loading the GA script would be the least of their worries.

**Comment by lucendio** [comment]
In my opinion, we as developer have a responsibility to our users. that said security and safety has to be our highest priority. And if the result will be nothing more then a bit more noise on the web, which makes mass surveillance a tiny little bit more harder, okay fine by me. And if I simply have to change some 's' in some places to lower down the vulnerability of my platform, awesome. 

google is going to rank sites without a TLS connection, lower then the one with a secure connection. we 2015, no https is no option any more.

A man in the middle attack is not that unlikely. If the chances are still 1 to 1 Mio or higher, the possibility exists no matter what. I personally like to exclude every contingency, if I am able to.

If you dont agree in some point, okay, no problem. I install my fork. But would suggest you leaving a note in the readme.

**Comment by reywood** [comment]
I understand and appreciate your concerns, but this change does not provide any added security. If your site is served up over HTTPS, then the GA scripts will already be downloaded over HTTPS as well. Your change is not necessary to accomplish that. If you fear your users are at risk for a man-in-the-middle attack and your site is **not** served over HTTPS, then serving the GA scripts over HTTPS does not make them any more secure. It only provides a false sense of security which is arguably worse. Again, I do appreciate and thank you for the effort.

**Comment by lucendio** [comment]
You have a point (in the argumentation about the technical mechanisms), I have to admit, but I think we disagree on that point in a more general perspective. I criticize the fact not forcing a secure connection.
but its great to see that there is awareness of the situation on your side. I think, we can leave it at that. For me, I am a fan of explicitness and will choose it over implicitness any time.
many thanks, and if its the case, sorry for stealing your time.

**Pull request closed without merging**
